---
- name: build server
  hosts: build
  become: yes

  tasks:
  - name: install git, java and maven
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
      - git
      - java-1.8.0-openjdk
      - maven

  - name: Clone a github repository
    git:
      clone: yes
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /opt/boxfuse

  #- name: git clone
  #- name: maven zborka java prilojenie and i will have artifact
  #- name: deploy artfact to prod
  