---
- name: prod zerver
  hosts: prod
  become: yes

  tasks:
    - name: install tomcat
      command: "{{ item }}"
      loop:
        - sudo apt update
        - sudo apt upgrade -y
        - sudo apt install openjdk-8-jdk -y
        - sudo apt install tomcat9 tomcat9-admin tomcat9-docs tomcat9-common -y

    - name: deploy artifact
      copy:
        src: hello-1.0.war
        dest: /var/lib/tomcat9/webapps/hello.war