---
- name: zborka server
  hosts: zborka
  become: yes

  tasks:
  - name: install git, java, maven, tmux, mc
    yum:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
      - git
      - java-1.8.0-openjdk
      - maven
      - tmux
      - mc

  - name: Clone a github repository
    git:
      clone: yes
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /opt/boxfuse

  #- name: git clone
  #- name: maven zborka java prilojenie and i will have artifact
  #- name: deploy artfact to prod
  