---
- name: create EC2 Instance on AWS via Ansible
  hosts: localhost
  gather_facts: false
  tasks:
    - name: create a new EC2 key pair, returns generated private key
      ec2_key:
        name: keypair
        region: us-east-1
      register: keyinfo

   # - name: Print key
   #   debug:
   #    var: keyinfo

    - name: save keypair.pem
      copy:
        content: "{{keyinfo.key.private_key}}"
        dest: ./keypair.pem
      when: keyinfo.changed