---
- name: create EC2 Instance on AWS via Ansible
  hosts: localhost
  gather_facts: false
  tasks:
    - name: create a new EC2 key pair, returns generated private key
      ec2_key:
        name: keypair3
        region: us-east-1
      register: keyinfo

    - debug:
        var: keyinfo.key.private_key

    - name: save keypair.pem
      copy:
        content: "{{ keyInfo.key.private_key }}"
        dest: keypair.pem